### ISSUE TITLE
Nucleic acid builder missing in opensource version

### ISSUE THREAD

**Issue by pacho2** [schrodinger/pymol-open-source#102]
I was looking for
https://pymolwiki.org/index.php/Builder

I couldn't find in my pymol, neither in pmg_qt/builder.py

Then, I saw it's in the commercial version... is that intentional or would it be possible to add it to opensource one?

Thanks a lot

**Comment by speleo3** [comment]
Thanks for your interest in the Nuceic Acid Builder. It's intentional that this feature has not been released as Open-Source yet and we have no short-term plans to do so.

**Comment by JarrettSJohnson** [comment]
Closing this ticket since it's been over a year. Some incentive features do find their way to open-source, but as Thomas mentioned last year there are no current plans of migrating this to open-source. If we do, however, it'll be posted in the corresponding release notes and if I'm able to, I'll make a mention of it in this ticket.
