### ISSUE TITLE
ray_interior_color atomic not working properly 

### ISSUE THREAD

**Issue by giagitom** [schrodinger/pymol-open-source#120]
Hi, 
when I `set ray_interior_color, atomic` and render the scene i get a uniform coloring instead. 
![Screenshot 2020-07-30 14:56:25](https://user-images.githubusercontent.com/20627977/88925504-e77d2880-d274-11ea-973f-3904cb99c218.png)

**Comment by speleo3** [comment]
I've marked this as a feature request. I think it's reasonable to support this, but want to spec out the expected behavior before implementing.

I assume you expect that a sphere with color `yellow` and `ray_interior_color=atomic` will have a yellow interior color (color of current primitive), and not the color you'd get from `color atomic`.

That would yield the following support table for `ray_interior_color`:

<table>
<tr><td><b>Setting value</td><td><b>Effective Color</td></tr>
<tr><td><a href="https://pymolwiki.org/index.php/Color_Values">named color</a></td><td>named color</td></tr>
<tr><td><a href="https://pymolwiki.org/index.php/Ramp_New">name of color ramp</a></td><td> ramp lookup at front clipping plane</td></tr>
<tr><td>object</td><td>object color</td></tr>
<tr><td>atomic</td><td>color of current primitive <b>(new)</b></td></tr>
</table>

Different contexts for the `atomic` color:

<table>
<tr><td><b>Command</td><td><b>Effect</td></tr>
<tr><td><a href="https://pymolwiki.org/index.php/Color#Color_by_element.2C_except_carbons">color</a></td><td>Assigns element colors to atoms</td></tr>
<tr><td><a href="https://pymolwiki.org/index.php/Ramp_New#Supported_special_colors">ramp_new</a></td><td>color of closest atom in proximity object</td></tr>
<tr><td><a href="https://pymolwiki.org/index.php/Set">set</a> ray_interior_color, atomic</td><td>ray interior coloring by current primitive color <b>(new)</b></td></tr>
</table>

**Comment by giagitom** [comment]
Yes, exactly. 
It would be nice to implement this feature.

**Comment by giagitom** [comment]
Thank you @speleo3 i tried the new feature and looks really nice!

Would it be possible to scale (darken a bit) interior color when atomic coloring is set? This is to better discriminate internal from the external parts. I tried to scale interior color by 0.8 factor in the below image.

I also found strange artifacts when rendering spheres together with cartoons as you can see 
![Screenshot 2020-08-06 17:15:27](https://user-images.githubusercontent.com/20627977/89549333-79061080-d808-11ea-9d87-7959f9495ef8.png)

**Comment by speleo3** [comment]
@giagitom you can control the brightness to some extent with the `direct` and `reflect` settings.

Side note: I thought we now match lighting properly in ray tracing and shader rendering, but it appears not to be the case for these two settings.

Not sure if there is much we can do about the artifacts.

**Comment by giagitom** [comment]
Thanks @speleo3 .

Do you know what is the cause of artifacts? Because it is not only related to cartoons only. If i apply any representation other than spheres to the scene it breaks color sorting for some reason.

**Comment by giagitom** [comment]
> Not sure if there is much we can do about the artifacts.

@speleo3 any news on the artifacts cause? I am wondering if you know why this is happening

**Comment by speleo3** [comment]
> any news on the artifacts cause? I am wondering if you know why this is happening

We don't know yet, sorry :-(
