### ISSUE TITLE
`h_add` depends on "state"?

### ISSUE THREAD

**Issue by aanastasiou** [schrodinger/pymol-open-source#127]
The following two snippets produce different output, depending on the order of commands:

1. `delete all;fetch 1GCN; hide all;select bb, backbone; select sc, sidechain;deselect;h_add bb;show sticks, bb`

2. `delete all;fetch 1GCN; hide all;select bb, backbone; select sc, sidechain;deselect;show sticks, bb; h_add bb`

The expected behaviour is what the second snippet achieves. I have also tried adding `refresh` on the first snippet, just to see if it is something to do with not having updated the visual state but there was no improvement. Hydrogens do not seem to be added (?).

**Comment by speleo3** [comment]
`h_add bb` will add hydrogens but it will not update the `bb` selection, so `show sticks, bb` will only affect the previously present atoms.

Another issue is that `h_add` does not add hydrogens with standard PDB names, but simply names them "H01", "H02", etc. and the `backbone` selection only detects atoms with standard names. So `show sticks, backbone` does still not pick up the added atoms, unfortunately.

`h_add` adds hydrogens with the same representation as the existing atoms, that's why the second example shows them as sticks.

**Comment by aanastasiou** [comment]
@speleo3 Thank you, that is clear, albeit slightly frustrating :) 
As an outsider's naive question: Do you think that would take a lot of work to add as a feature? I would be interested in giving it a go (with some guidance).
