### ISSUE TITLE
Anaconda dependency issues 

### ISSUE THREAD

**Issue by jlaw9** [schrodinger/pymol-open-source#19]
I just tried installing pymol using the latest anaconda (fresh install version 2018.12, Python 3.7 on Linux Mint 19), and I get the following error:

```
$ conda install -c schrodinger pymol
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - anaconda==2018.12=py37_0 -> cython==0.29.2=py37he6710b0_0
  - anaconda==2018.12=py37_0 -> mkl-service==1.1.2=py37he904b0f_5
  - anaconda==2018.12=py37_0 -> numexpr==2.6.8=py37h9e4a6bb_0
  - anaconda==2018.12=py37_0 -> scikit-learn==0.20.1=py37hd81dba3_0
  - pymol
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by speleo3** [comment]
Our python 3.7 builds will make it into "main" label soon. Until then, please install python 3.6 or check out https://pymol.org/alpha

**Comment by jlaw9** [comment]
ah ok thanks

**Comment by speleo3** [comment]
python 3.7 builds now available by default, see https://anaconda.org/schrodinger/pymol

**Comment by bionicles** [comment]
@speleo3 conda install -c schrodinger pymol adds the GUI command for running from bash, but it doesnt properly update the pythonpath ... when you run python 3.7 after conda install, and try 

from pymol import cmd
it reads, "ImportError: No module named pymol" 

great, so i added /usr/local/Cellar/pymol/2.2.0/libexec/lib/python3.7/site-packages/pymol to PYTHONPATH in .bash_profile 

now it still fails, because pymol/cmd.py can't find pymol ? how does that make sense?

well, there's a pymol_path folder inside site-packages/pymol. why is pymol_path not actually the path to pymol? plus, even worse, there's **site-packages/pymol2/cmd2.py** ??? why are there two cmd files and which one are we supposed to use in python scripts?

conda install should tell python where pymol lives so every user doesn't have to waste an hour figuring hour how to properly tell python where to find the thing they just installed
