### ISSUE TITLE
Aligning 2 small molecules in PyMOL

### ISSUE THREAD

**Issue by Bio-Otto** [schrodinger/pymol-open-source#194]
Hi,
When I try to align 2 ligands molecules in Pymol, it gives a warning like `ExecutiveAlign: mobile selection must derive from one object only` But if I do the same operation as `align ligand1, ligand2` from the command, the calculation takes place.  In addition, this situation is also stated on [StackOverflow.](https://stackoverflow.com/questions/16546514/aligning-2-small-molecules-in-pymol)

**Comment by JarrettSJohnson** [comment]
The command from the internal GUI calls this command under the hood:

```
align polymer and name CA and obj1, organic and name CA and obj2, object="aln_obj1_to_obj2", reset=1
```
where obj1 and obj2 are the objects you're trying to 'align'. As mentioned in that stack overflow post, the align method performs a sequence-based alignment followed by a structure alignment *of atoms aligned from the first*. This approach seems to be meant for aligning protein pairs. Finding a meaningful superposition of a ligand pair, especially if they're of wildly varying lengths, is something that I don't think is trivial. As mentioned in that post as well though, however, if you have a region that of the ligand whose atom numbers are the same and you want to superimpose, that is doable.

If anything, I can agree that it is a bit deceptive since this command is hidden away--we'll probably consider renaming the command to 'align protein' or similar instead.

**Comment by Bio-Otto** [comment]
Thank you so much for clarify the issue
