### ISSUE TITLE
Rendering problem on `mpng`

### ISSUE THREAD

**Issue by YoshitakaMo** [schrodinger/pymol-open-source#25]
Hi, I tried to use `mpng foo` command to output sequential png images of multistate objects on macOS 10.14.3, the images were created, but a warning message `WARNING: glReadBuffer caused GL error 0x0502` was displayed and they were slightly odd -- all line objects were always displayed on the cartoon objects (left). When using `png bar.png` command to save the image, this issue did not happen (right).

I found that this issue happened on both macOS 10.13 and 10.14, and on both Open-source and DMG diskimage versions. The PyMOL version was 2.3.0. Interestingly, the issue does not happen on Ubuntu 18.04 with NVidia RTX 2080Ti.

Here is the command I input to create the image below:
```
fetch 1alk
mpng foo
png bar.png
```

![graphic](https://user-images.githubusercontent.com/16487484/54008547-60746f80-41aa-11e9-8c21-27acf6994104.png)

**Comment by speleo3** [comment]
Thanks a lot for this detailed bug report! I can reproduce it. Looks like depth testing is messed up (I also see ordering artifacts in the cartoon part).

I assume this is related to using [QOpenGLWidget](https://doc.qt.io/qt-5/qopenglwidget.html). On macOS, [PyMOL uses QOpenGLWidget](https://github.com/schrodinger/pymol-open-source/blob/master/modules/pmg_qt/pymol_gl_widget.py#L21) because it fixes a UI issue. On Linux and Windows we use [QGLWidget](https://doc.qt.io/qt-5/qglwidget.html).

**Comment by speleo3** [comment]
We still haven't figured this out properly, but there is a workaround:
```
mpng foo, modal=1
```
