### ISSUE TITLE
Undo has been disabled. Reason: Object is too large

### ISSUE THREAD

**Issue by ValZapod** [schrodinger/pymol-open-source#256]
set assembly, 1
fetch 7TBM, assembly1, async=0

set grid_mode

**Comment by JarrettSJohnson** [comment]
Thanks for reporting this issue. Currently, the `set` command copies a lot of data in the session to account for side-effects that can occur. We're planning to address this issue in a future release.

Since this feature is incentive-only and not available to open-source, I'll go ahead and close this issue. For any other queries and support for incentive-only features, they should be directed to help@schrodinger.com
