### ISSUE TITLE
Cartoon_trancparency command not working after using it on specific residue ranges

### ISSUE THREAD

**Issue by TheWizier** [schrodinger/pymol-open-source#269]
Reproduce:
cmd.set("cartoon_transparency", 0.5, "not i. 12-38")
cmd set("cartoon_transparency", 1)

Outcome: Second command does nothing.
Expected outcome: All cartoons become fully transparent.

**Comment by JarrettSJohnson** [comment]
This is likely expected since the first command provides a selection which applies the transparency on the atomic level which the second command does not. If you want all parts of all cartoons to be transparent, either unset the setting on the atomic level by applying `unset_deep cartoon_transparency` (and then perform the second command) or apply transparency on the atomic level by providing a selection which describes all atoms (e.g. `set cartoon_transparency, 1.0, (all)`)

**Comment by JarrettSJohnson** [comment]
Feel free to reopen if the comment doesn't address your needs.
