### ISSUE TITLE
Missing functions called from `movie.add_scenes()`

### ISSUE THREAD

**Issue by jaredsampson** [schrodinger/pymol-open-source#29]
The "Movie > Program > Scene Loop" menu item calls `movie.add_scenes(names=None, ...)`.  The docstring specifies that names can also be a `str` list of scene names, but if called with a string, results in a traceback.

```
PyMOL>frag ala
 Executive: object "ala" created.
PyMOL>scene F1, store
 scene: scene stored as "F1".
PyMOL>movie.add_scenes('F1')
Traceback (most recent call last):
  File "/Users/jared/.local/miniconda3/lib/python3.6/site-packages/pymol/movie.py", line 612, in add_scenes
    elif cmd.is_str(names):
AttributeError: module 'pymol.cmd' has no attribute 'is_str'
```
It turns out `cmd.is_str()` no longer exists (anywhere) in the codebase, and `cmd.safe_alpha_list_eval()` has been moved to `pymol.constants`.

Ultimately, `names` is expected to be a Python `list` of strings (as in the output from `cmd.get_scene_list()`, so it would be helpful if such a list could also be passed via the API.

**Comment by speleo3** [comment]
Replacing `cmd.is_str(names)` with `cmd.is_string(names)` should fix this.

Note: Evaluating names from a string allows using `add_scenes` as a command:
```
PyMOL> cmd.extend(movie.add_scenes)
PyMOL> add_scenes [foo, bar]
```

**Comment by jaredsampson** [comment]
I notice that `pymol.cmd` isn't imported via `import`, but via

```
cmd = sys.modules["pymol.cmd"]
```

Is this a pattern I should follow to import `constants` as well?  What is the purpose of using this rather than an import statement?

**Comment by speleo3** [comment]
That pattern is a workaround for circular imports. `pymol.cmd` should be the only module which needs this workaround.

Note that `pymol.constants` is usually not imported directly. There is a `from .constants import *` in `pymol/cmd.py`, so calling `cmd.safe_alpha_list_eval()` is fine. (On the other hand, since these are constants which have no dependency on the PyMOL instance, using `cmd` is kind of an anti-pattern here).
