### ISSUE TITLE
Missing tags for versions 2.3.1, 2.3.2, 2.3.3

### ISSUE THREAD

**Issue by llimeht** [schrodinger/pymol-open-source#50]
Tags for pymol releases 2.3.1, 2.3.2, 2.3.3 are not visible on GitHub. It's possible that the releases weren't tagged, are on a maintenance branch that has not been pushed to GitHub or simply that the tags were not pushed to GitHub. It'd be great if releases were clearly tagged.

**Comment by speleo3** [comment]
We don't publish maintenance releases for Open-Source PyMOL. Fixes go directly into master (development version) along with new features. So between versions, Incentive PyMOL and Open-Source PyMOL won't be 100% in sync.

For Incentive PyMOL (https://pymol.org/#download ) we internally maintain branches for bugfix releases.

**Comment by sagitter** [comment]
Hi.

>We don't publish maintenance releases for Open-Source PyMOL.

How do we know when Open-Source PyMOL is sufficiently mature to be recompiled as new release?
I see "_PYMOL-xxxx_" sometimes in your commits, what does that mean?

**Comment by JarrettSJohnson** [comment]
For now, if you're looking for the most stable builds, I'd suggest compiling up to versions that end in ".0" since these will correlate with Incentive PyMOL releases and have undergone a more thorough review than what [pymol-testing](https://github.com/schrodinger/pymol-testing) provides.

The "PYMOL-XXXX" are used for our internal issue tracking system.

**Comment by JarrettSJohnson** [comment]
Closing this issue. We may address this with an alternative for this in the future, but for now just the major releases are tagged.
